version: '2'
services:
  web:
    build:
      context: ./docker
      dockerfile: Dockerfile.dev
    volumes:
      - .:/var/www/app
      # TODO: temporary workaround for public web-root
      - ./public:/app/web
      # host-volume for composer cache
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ~/.composer:/var/www/.composerhost
      - ~/.ssh:/var/www/.ssh
    ports:
      - '8000:80'
    links:
      - db
  db:
    image: mariadb:latest
    ports:
      - 3306
    environment:
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
