version: '2'
services:
  web:
    build:
      context: ./docker
      dockerfile: Dockerfile.dev
    volumes:
      - .:/var/www/app
      # TODO: temporary workaround for public web-root
      - ./public:/app/web
      # host-volume for composer cache
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ~/.composer:/var/www/.composerhost
      - ~/.ssh:/var/www/.ssh
    environment:
      DB_DSN: mysql:host=db;dbname=database
      DB_TEST_DSN: mysql:host=dbtest;dbname=database_test
      DB_USER: user
      DB_PASS: pass
    ports:
      - '8000:80'
    links:
      - db
      - dbtest
  db:
    image: mariadb:latest
    ports:
      - 3306
    environment:
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
  dbtest:
    image: mariadb:latest
    ports:
      - 3306
    environment:
      MYSQL_DATABASE: database_test
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - dbtest_data:/var/lib/mysql
volumes:
  db_data:
  dbtest_data:
