<?php

namespace app\modules\api\domains\favorite;

use app\modules\api\domains\article\Article;
use app\modules\api\domains\user\User;

class Favorite extends \app\domains\favorite\Favorite
{
    protected $articleClass = Article::class;
    protected $userClass = User::class;

    public function fields()
    {
        return parent::fields(); // TODO: Change the autogenerated stub
    }

}
